DELIMITER //

CREATE PROCEDURE GetAlertModule(

	In partyRoleId int(10),
	In AlertModuleName varchar(64),
	In IsEnabled char(1)
)
BEGIN
	from OB_NOTICE_DETAIL,OB_NOTICE_EMAIL_DETAIL,OB_NOTICE_EMAIL_SUBSCRIPTION
	
	INNER JOIN OB_NOTICE_EMAIL_DETAIL ON
	OB_NOTICE_DETAIL.ID=OB_NOTICE_EMAIL_DETAIL.NOTICE_DETAIL_ID
	INNER JOIN OB_NOTICE_EMAIL_SUBSCRIPTION ON
	OB_NOTICE_EMAIL_SUBSCRIPTION.ID=OB_NOTICE=EMAIL_DETAIL.NOTICE_EMAIL_DETAIL_ID.;
	
	
	
	UPDATE OB_NOTICE_EMAIL_SUBSCRIPTION
            
            SET
            PARTY_ROLE_ID=partyRoleId,
            ALERT_NAME=AlertModuleName,
            ENABLED=ISENABLED
            
END //

DELIMITER ;
